#!/usr/bin/env bash
# Configures an Ubuntu server so localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8
sed -i 's/127.0.0.1\s*localhost/127.0.0.2 localhost/' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
